/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'

export default function VanGlb(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/AllColorGLB144/$39000-first-option.glb')
  const { actions } = useAnimations(animations, group)
// console.log("Nodes:", nodes);
// console.log("Materials:", materials);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Invertor_charger_3000"
          castShadow
          receiveShadow
          geometry={nodes.Invertor_charger_3000.geometry}
          material={materials['Invertor charger 3000']}
          position={[-0.553, 0.815, -1.56]}
        />
        <mesh
          name="_600_no_heat_battery"
          castShadow
          receiveShadow
          geometry={nodes._600_no_heat_battery.geometry}
          material={materials['Material.005']}
          position={[-0.569, 0.592, -1.518]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.01}
        />
        <group
          name="UNDRDSHAIRCNDCNREVPRTR"
          position={[-0.279, 0.733, -1.704]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.01}>
          <mesh
            name="Mesh006"
            castShadow
            receiveShadow
            geometry={nodes.Mesh006.geometry}
            material={materials.Black}
          />
          <mesh
            name="Mesh006_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh006_1.geometry}
            material={materials.Gold}
          />
          <mesh
            name="Mesh006_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh006_2.geometry}
            material={materials.Matel}
          />
          <mesh
            name="Mesh006_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh006_3.geometry}
            material={materials['W.001']}
          />
          <mesh
            name="Mesh006_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh006_4.geometry}
            material={materials.Org}
          />
        </group>
        <group
          name="Sketchfab_model"
          position={[-1.534, -0.164, 0.358]}
          rotation={[-1.576, -0.002, 0.001]}
          scale={0.005}>
          <group name="c9e9a36133ba470dbcac56530ae19111fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="MotorOil_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="MotorOil_low_Rust_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.MotorOil_low_Rust_0.geometry}
                  material={materials['Material.019']}
                  position={[2.168, 4.532, 1.925]}
                  rotation={[0.007, -0.003, 1.571]}
                  scale={0.203}
                />
              </group>
            </group>
          </group>
        </group>
        <mesh
          name="UNDRDSHAIRCNDCNREVPRTR001"
          castShadow
          receiveShadow
          geometry={nodes.UNDRDSHAIRCNDCNREVPRTR001.geometry}
          material={materials.Black}
          position={[-0.279, 0.733, -1.704]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.01}
        />
        <mesh
          name="EFI535004"
          castShadow
          receiveShadow
          geometry={nodes.EFI535004.geometry}
          material={materials['white.002']}
          position={[-0.244, 0.994, -1.764]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="EFI535005"
          castShadow
          receiveShadow
          geometry={nodes.EFI535005.geometry}
          material={materials['white.002']}
          position={[0.249, 0.994, -1.764]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.001}
        />
        <group
          name="AC_down_001"
          position={[-0.241, 0.958, -1.562]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={1.047}>
          <mesh
            name="Cube022"
            castShadow
            receiveShadow
            geometry={nodes.Cube022.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Cube022_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube022_1.geometry}
            material={materials.Material}
          />
        </group>
        <group
          name="AC_down_002"
          position={[-0.241, 0.957, -1.624]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={1.047}>
          <mesh
            name="Cube002_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Cube002_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_2.geometry}
            material={materials.Material}
          />
        </group>
        <group
          name="AC_down_003"
          position={[-0.241, 0.958, -1.687]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={1.047}>
          <mesh
            name="Cube006"
            castShadow
            receiveShadow
            geometry={nodes.Cube006.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Cube006_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_1.geometry}
            material={materials.Material}
          />
        </group>
        <group
          name="AC_down_004"
          position={[-0.241, 0.957, -1.75]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={1.047}>
          <mesh
            name="Cube007"
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Cube007_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube007_1.geometry}
            material={materials.Material}
          />
        </group>
        <group
          name="AC_down_005"
          position={[-0.241, 0.958, -1.814]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={1.047}>
          <mesh
            name="Cube010"
            castShadow
            receiveShadow
            geometry={nodes.Cube010.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Cube010_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_1.geometry}
            material={materials.Material}
          />
        </group>
        <group
          name="AC_down_006"
          position={[-0.241, 0.957, -1.876]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={1.047}>
          <mesh
            name="Cube011"
            castShadow
            receiveShadow
            geometry={nodes.Cube011.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Cube011_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube011_1.geometry}
            material={materials.Material}
          />
        </group>
        <mesh
          name="DC-DC_Charger_#1964"
          castShadow
          receiveShadow
          geometry={nodes['DC-DC_Charger_#1964'].geometry}
          material={materials.Text}
          position={[-0.362, 0.828, -1.382]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.01}
        />
        <mesh
          name="DC-DC_Charger_#1964001"
          castShadow
          receiveShadow
          geometry={nodes['DC-DC_Charger_#1964001'].geometry}
          material={materials.Text}
          position={[-0.359, 0.817, -1.273]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.01}
        />
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials['Material.004']}
          position={[-0.358, 0.806, -1.383]}
          scale={[0.226, 0.199, 0.397]}
        />
        <mesh
          name="Cube009"
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials.black}
          position={[-0.517, 0.794, -2.278]}
        />
        <group name="Empty" position={[-0.777, 1.011, -2.282]} scale={0.225}>
          <group
            name="EFI64001"
            position={[1.186, 0, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.004, 0.005, 0.004]}>
            <mesh
              name="EFI64001_1"
              castShadow
              receiveShadow
              geometry={nodes.EFI64001_1.geometry}
              material={materials['white.002']}
            />
            <mesh
              name="EFI64001_2"
              castShadow
              receiveShadow
              geometry={nodes.EFI64001_2.geometry}
              material={materials['Material.003']}
            />
          </group>
        </group>
        <mesh
          name="Plane022"
          castShadow
          receiveShadow
          geometry={nodes.Plane022.geometry}
          material={materials['white.002']}
          position={[0.391, 2.392, 0.344]}
        />
        <mesh
          name="BézierCurve003"
          castShadow
          receiveShadow
          geometry={nodes.BézierCurve003.geometry}
          material={materials['Material.006']}
          position={[0.634, 2.338, 0.394]}
        />
        <mesh
          name="Cube002"
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials['white.002']}
          position={[0.705, 2.232, -0.347]}
        />
        <mesh
          name="NONE_15001"
          castShadow
          receiveShadow
          geometry={nodes.NONE_15001.geometry}
          material={materials['Material.042']}
          position={[0.403, 2.208, -0.107]}
        />
        <mesh
          name="NONE_15002"
          castShadow
          receiveShadow
          geometry={nodes.NONE_15002.geometry}
          material={materials['Material.042']}
          position={[0.403, 2.208, -0.528]}
        />
        <mesh
          name="NONE_15003"
          castShadow
          receiveShadow
          geometry={nodes.NONE_15003.geometry}
          material={materials['Material.042']}
          position={[0.403, 2.208, -0.949]}
        />
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials['white.002']}
          position={[-0.057, 2.572, -0.862]}
        />
        <group name="Empty001" position={[-0.777, 1.019, -1.592]} scale={0.266}>
          <group
            name="EFI182001"
            position={[6.07, -1.758, -3.959]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.004}>
            <mesh
              name="EFI182001_1"
              castShadow
              receiveShadow
              geometry={nodes.EFI182001_1.geometry}
              material={materials['Material.003']}
            />
            <mesh
              name="EFI182001_2"
              castShadow
              receiveShadow
              geometry={nodes.EFI182001_2.geometry}
              material={materials['white.002']}
            />
          </group>
        </group>
        <group
          name="начальный004"
          position={[1.282, 2.295, -0.193]}
          rotation={[Math.PI / 2, 0, 1.578]}
          scale={0.001}
        />
        <group name="Van_body002" position={[0.101, 1.17, 1.168]}>
          <mesh
            name="Mesh003"
            castShadow
            receiveShadow
            geometry={nodes.Mesh003.geometry}
            material={materials['MainBody.001']}
          />
          <mesh
            name="Mesh003_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh003_1.geometry}
            material={materials['MainBody.002']}
          />
          <mesh
            name="Mesh003_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh003_2.geometry}
            material={materials['Glass.002']}
          />
        </group>
        <mesh
          name="rear_door003"
          castShadow
          receiveShadow
          geometry={nodes.rear_door003.geometry}
          material={materials['white material']}
          position={[0.419, 1.526, -2.762]}
        />
        <mesh
          name="rear_door004"
          castShadow
          receiveShadow
          geometry={nodes.rear_door004.geometry}
          material={materials['white material']}
          position={[-0.423, 1.528, -2.762]}
        />
        <mesh
          name="driver_side002"
          castShadow
          receiveShadow
          geometry={nodes.driver_side002.geometry}
          material={materials['Material.024']}
          position={[0.805, 1.589, -0.995]}
        />
        <mesh
          name="driver_side001"
          castShadow
          receiveShadow
          geometry={nodes.driver_side001.geometry}
          material={materials['DriverSide.001']}
          position={[0.829, 1.832, -1.337]}
        />
        <mesh
          name="Top001"
          castShadow
          receiveShadow
          geometry={nodes.Top001.geometry}
          material={materials['RoofTop.001']}
          position={[0.002, 2.594, -1.136]}
        />
        <mesh
          name="Van_body001"
          castShadow
          receiveShadow
          geometry={nodes.Van_body001.geometry}
          material={materials['RearDoor.001']}
          position={[0.03, 1.372, -2.807]}
        />
        <mesh
          name="Van_body003"
          castShadow
          receiveShadow
          geometry={nodes.Van_body003.geometry}
          material={materials['floor.001']}
          position={[0.101, 1.17, 1.168]}
        />
        <group name="stationary_double_seat001" position={[0.545, 1.175, -0.234]}>
          <mesh
            name="trunk_part_39002"
            castShadow
            receiveShadow
            geometry={nodes.trunk_part_39002.geometry}
            material={materials['black.002']}
          />
          <mesh
            name="trunk_part_39002_1"
            castShadow
            receiveShadow
            geometry={nodes.trunk_part_39002_1.geometry}
            material={materials['Material.094']}
          />
          <mesh
            name="trunk_part_39002_2"
            castShadow
            receiveShadow
            geometry={nodes.trunk_part_39002_2.geometry}
            material={materials['Material.095']}
          />
          <mesh
            name="trunk_part_39002_3"
            castShadow
            receiveShadow
            geometry={nodes.trunk_part_39002_3.geometry}
            material={materials['black.004']}
          />
          <mesh
            name="trunk_part_39002_4"
            castShadow
            receiveShadow
            geometry={nodes.trunk_part_39002_4.geometry}
            material={materials['red.002']}
          />
          <mesh
            name="trunk_part_39002_5"
            castShadow
            receiveShadow
            geometry={nodes.trunk_part_39002_5.geometry}
            material={materials['black.005']}
          />
          <mesh
            name="trunk_part_39002_6"
            castShadow
            receiveShadow
            geometry={nodes.trunk_part_39002_6.geometry}
            material={materials['chrome.002']}
          />
          <mesh
            name="trunk_part_39002_7"
            castShadow
            receiveShadow
            geometry={nodes.trunk_part_39002_7.geometry}
            material={materials['chrome.006']}
          />
        </group>
        <mesh
          name="eBom-FreePartsstpSLDPRT"
          castShadow
          receiveShadow
          geometry={nodes['eBom-FreePartsstpSLDPRT'].geometry}
          material={materials['white.002']}
          position={[-0.625, 1.747, -1.17]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="�������-�������61_3002"
          castShadow
          receiveShadow
          geometry={nodes['�������-�������61_3002'].geometry}
          material={materials['white.002']}
          position={[0.393, 2.357, -0.107]}
          scale={[1, 1, 1.006]}
        />
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials['white.002']}
          position={[0.539, 1.406, -1.169]}
        />
        <mesh
          name="�������-�������61_3004"
          castShadow
          receiveShadow
          geometry={nodes['�������-�������61_3004'].geometry}
          material={materials['white.002']}
          position={[0.393, 2.357, -0.528]}
          scale={[1, 1, 1.006]}
        />
        <mesh
          name="�������-�������61_3005"
          castShadow
          receiveShadow
          geometry={nodes['�������-�������61_3005'].geometry}
          material={materials['white.002']}
          position={[0.393, 2.357, -0.949]}
          scale={[1, 1, 1.006]}
        />
        <mesh
          name="�����-�������4_6"
          castShadow
          receiveShadow
          geometry={nodes['�����-�������4_6'].geometry}
          material={materials['white.002']}
          position={[0.835, 0.552, -2.644]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Plane003"
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={nodes.Plane003.material}
          position={[0.835, 0.552, -2.644]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.271, 0.239, 0.206]}
        />
        <group
          name="justin"
          position={[0.835, 0.552, -2.644]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.001}>
          <mesh
            name="Boss-Extrude1_19"
            castShadow
            receiveShadow
            geometry={nodes['Boss-Extrude1_19'].geometry}
            material={materials['white.002']}
          />
          <mesh
            name="Boss-Extrude1_20"
            castShadow
            receiveShadow
            geometry={nodes['Boss-Extrude1_20'].geometry}
            material={materials['white.002']}
          />
          <mesh
            name="Boss-Extrude1_21"
            castShadow
            receiveShadow
            geometry={nodes['Boss-Extrude1_21'].geometry}
            material={materials['Wooden ']}
          />
          <mesh
            name="EFI182002"
            castShadow
            receiveShadow
            geometry={nodes.EFI182002.geometry}
            material={nodes.EFI182002.material}
          />
          <mesh
            name="EFI231001"
            castShadow
            receiveShadow
            geometry={nodes.EFI231001.geometry}
            material={nodes.EFI231001.material}
          />
          <mesh
            name="EFI242001"
            castShadow
            receiveShadow
            geometry={nodes.EFI242001.geometry}
            material={materials['white.002']}
          />
          <mesh
            name="EFI288001"
            castShadow
            receiveShadow
            geometry={nodes.EFI288001.geometry}
            material={materials['Wooden ']}
          />
          <mesh
            name="EFI350001"
            castShadow
            receiveShadow
            geometry={nodes.EFI350001.geometry}
            material={materials['white.002']}
          />
          <group name="EFI64002">
            <mesh
              name="EFI64002_1"
              castShadow
              receiveShadow
              geometry={nodes.EFI64002_1.geometry}
              material={materials['white.002']}
            />
            <mesh
              name="EFI64002_2"
              castShadow
              receiveShadow
              geometry={nodes.EFI64002_2.geometry}
              material={materials['Material.003']}
            />
          </group>
          <mesh
            name="EFI71_2"
            castShadow
            receiveShadow
            geometry={nodes.EFI71_2.geometry}
            material={materials['white.002']}
          />
          <mesh
            name="Pah1_2"
            castShadow
            receiveShadow
            geometry={nodes.Pah1_2.geometry}
            material={materials['Material.003']}
            position={[-1717.788, 728.987, -465.337]}
          />
          <mesh
            name="Pah1_2001"
            castShadow
            receiveShadow
            geometry={nodes.Pah1_2001.geometry}
            material={materials['Material.003']}
            position={[-1677.089, 728.988, -466.15]}
          />
          <mesh
            name="Pah1_5"
            castShadow
            receiveShadow
            geometry={nodes.Pah1_5.geometry}
            material={materials['Material.003']}
          />
          <mesh
            name="Pah1_7001"
            castShadow
            receiveShadow
            geometry={nodes.Pah1_7001.geometry}
            material={materials['Material.003']}
            position={[-54.342, 80.762, -465.344]}
          />
          <mesh
            name="Pah1_7002"
            castShadow
            receiveShadow
            geometry={nodes.Pah1_7002.geometry}
            material={materials['Material.003']}
            position={[-54.342, 435.046, -465.344]}
          />
          <mesh
            name="Pah1_7003"
            castShadow
            receiveShadow
            geometry={nodes.Pah1_7003.geometry}
            material={materials['Material.003']}
            position={[-54.342, 565.206, -465.344]}
          />
          <mesh
            name="Pah1_7004"
            castShadow
            receiveShadow
            geometry={nodes.Pah1_7004.geometry}
            material={materials['Material.003']}
            position={[-54.342, 1247.001, -465.344]}
          />
          <mesh
            name="Pah1_8"
            castShadow
            receiveShadow
            geometry={nodes.Pah1_8.geometry}
            material={materials['Material.003']}
          />
          <mesh
            name="Pah1_8001"
            castShadow
            receiveShadow
            geometry={nodes.Pah1_8001.geometry}
            material={materials['Material.003']}
            position={[-89.265, 80.762, -465.344]}
          />
          <mesh
            name="Pah1_8002"
            castShadow
            receiveShadow
            geometry={nodes.Pah1_8002.geometry}
            material={materials['Material.003']}
            position={[-89.265, 435.046, -465.344]}
          />
          <mesh
            name="�����-�������1_16"
            castShadow
            receiveShadow
            geometry={nodes['�����-�������1_16'].geometry}
            material={materials['Wooden ']}
          />
          <mesh
            name="�����-�������2_13001"
            castShadow
            receiveShadow
            geometry={nodes['�����-�������2_13001'].geometry}
            material={materials['white.002']}
          />
          <mesh
            name="�����-�������2_14001"
            castShadow
            receiveShadow
            geometry={nodes['�����-�������2_14001'].geometry}
            material={materials['white.002']}
          />
          <mesh
            name="�����-�������2_15"
            castShadow
            receiveShadow
            geometry={nodes['�����-�������2_15'].geometry}
            material={nodes['�����-�������2_15'].material}
          />
          <mesh
            name="�����-�������2_16"
            castShadow
            receiveShadow
            geometry={nodes['�����-�������2_16'].geometry}
            material={nodes['�����-�������2_16'].material}
          />
          <mesh
            name="������1_11"
            castShadow
            receiveShadow
            geometry={nodes['������1_11'].geometry}
            material={materials['white.002']}
          />
          <mesh
            name="������1_12"
            castShadow
            receiveShadow
            geometry={nodes['������1_12'].geometry}
            material={materials['Wooden ']}
          />
          <mesh
            name="������1_13"
            castShadow
            receiveShadow
            geometry={nodes['������1_13'].geometry}
            material={materials['white.002']}
          />
          <mesh
            name="������1_14"
            castShadow
            receiveShadow
            geometry={nodes['������1_14'].geometry}
            material={materials['white.002']}
          />
          <mesh
            name="������1_15"
            castShadow
            receiveShadow
            geometry={nodes['������1_15'].geometry}
            material={materials['Wooden ']}
          />
          <mesh
            name="������1_16"
            castShadow
            receiveShadow
            geometry={nodes['������1_16'].geometry}
            material={materials['Wooden ']}
          />
          <mesh
            name="������1_17"
            castShadow
            receiveShadow
            geometry={nodes['������1_17'].geometry}
            material={materials['Wooden ']}
          />
          <mesh
            name="������2_2"
            castShadow
            receiveShadow
            geometry={nodes['������2_2'].geometry}
            material={materials['Wooden ']}
          />
          <mesh
            name="�������-�������1_8"
            castShadow
            receiveShadow
            geometry={nodes['�������-�������1_8'].geometry}
            material={nodes['�������-�������1_8'].material}
          />
          <mesh
            name="���������001"
            castShadow
            receiveShadow
            geometry={nodes['���������001'].geometry}
            material={nodes['���������001'].material}
          />
          <mesh
            name="����������1_10"
            castShadow
            receiveShadow
            geometry={nodes['����������1_10'].geometry}
            material={materials['Material.003']}
          />
          <mesh
            name="����������1_11"
            castShadow
            receiveShadow
            geometry={nodes['����������1_11'].geometry}
            material={materials['Material.003']}
          />
          <mesh
            name="����������1_12"
            castShadow
            receiveShadow
            geometry={nodes['����������1_12'].geometry}
            material={materials['Material.003']}
          />
          <mesh
            name="����������1_12001"
            castShadow
            receiveShadow
            geometry={nodes['����������1_12001'].geometry}
            material={materials['Material.003']}
            position={[-71.807, 80.759, -464.124]}
          />
          <mesh
            name="����������1_12002"
            castShadow
            receiveShadow
            geometry={nodes['����������1_12002'].geometry}
            material={materials['Material.003']}
            position={[-71.807, 435.042, -464.124]}
          />
          <mesh
            name="����������1_12003"
            castShadow
            receiveShadow
            geometry={nodes['����������1_12003'].geometry}
            material={materials['Material.003']}
            position={[-71.807, 565.203, -464.124]}
          />
          <mesh
            name="����������1_12004"
            castShadow
            receiveShadow
            geometry={nodes['����������1_12004'].geometry}
            material={materials['Material.003']}
            position={[-71.807, 1246.997, -464.124]}
          />
          <mesh
            name="����������1_9"
            castShadow
            receiveShadow
            geometry={nodes['����������1_9'].geometry}
            material={materials['Material.003']}
          />
        </group>
        <group name="UNC_Screw_Phillips_Pan_Head_8mm" position={[-0.747, 1.017, -2.557]} />
        <mesh
          name="EFI250001"
          castShadow
          receiveShadow
          geometry={nodes.EFI250001.geometry}
          material={materials['white.002']}
          position={[0.835, 0.552, -2.644]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.001}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/AllColorGLB144/$39000-first-option.glb')
