const interiorComponents = [

  {
    "category": "interior",
    "label": "Bamboo flooring",
    "price": 1000,
    "image": "/images/png/flooring-one.png",
    "component": "FlooringOne",
    "componentKey": "FlooringOne",
    "type": "flooring",
    "group": "Flooring",
    "description": "Narrow planks (three to five wide).",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Vinyl Marine Woven flooring",
    "price": 1000,
    "image": "/images/png/flooring-two.png",
    "component": "FlooringTwo",
    "componentKey": "FlooringTwo",
    "type": "flooring",
    "group": "Flooring",
    "description": "Waterproof and slip & stain-resistant.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Aquaguard Performance Laminate Flooring",
    "price": 1000,
    "image": "/images/png/flooring-three.png",
    "component": "FlooringThree",
    "componentKey": "FlooringThree",
    "type": "flooring",
    "group": "Flooring",
    "description": "Available in different colours, textures, and finishes.",
    "hasSink": false
  },
  {

    "category": "interior",
    "label": "Flooring Four",
    "price": 1000,
    "image": "/images/png/flooring-four.png",
    "component": "FlooringFour",
    "componentKey": "FlooringFour",
    "type": "flooring",
    "group": "Flooring",
    "description": "Basic flooring option four.",
    "hasSink": false
  },
  {

    "category": "interior",
    "label": "Front Jump Seat",
    "price": 1000,
    "image": "/images/png/jump-seat.png",
    "component": "JumpSeat",
    "componentKey": "JumpSeat",
    "type": "jumpseat",
    "group": "Driver's Area",
    "description": "An extra front seat between the driver's and passenger's seats.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Front Swivel Table with a Cup Holder",
    "price": 1000,
    "image": "/images/png/lagun-table.png",
    "component": "LagunTable",
    "componentKey": "LagunTable",
    "type": "jumpseat",
    "group": "Driver's Area",
    "description": "Can swivel between the front and 2nd row seats.",
    "hasSink": false
  },
  {

    "category": "interior",
    "label": "Overhead Open Storage",
    "price": 1000,
    "image": "/images/png/over-the-cab-storage-one.png",
    "component": "OverTheCabStorageOne",
    "componentKey": "OverTheCabStorageOne",
    "type": "storage",
    "group": "Driver's Area",
    "description": "Open shelving for easy luggage access.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Overhead Storage Cabinet",
    "price": 1000,
    "image": "/images/png/over-the-cab-storage-two.png",
    "component": "OverTheCabStorageTwo",
    "componentKey": "OverTheCabStorageTwo",
    "type": "storage",
    "group": "Driver's Area",
    "description": " Lockable enclosed cabinet for secure storage.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Curtain",
    "price": 1000,
    "image": "/images/png/curtain-one.png",
    "component": "CurtainOne",
    "componentKey": "CurtainOne",
    "type": "curtain",
    "group": "Driver's Area",
    "description": "To separate the driving area and living space for privacy.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Swivel Seat",
    "price": 1000,
    "image": "/images/png/swivel-seat.png",
    "component": "SwivelSeat",
    "componentKey": "SwivelSeat",
    "type": "swivelseat",
    "group": "Behind the Driver",
    "description": "Rotate 180° or 360° for flexible seating.",
    "hasSink": false
  },
  {

    "category": "interior",
    "label": "Upper Left Wall Cabinet With Microwave",
    "price": 1000,
    "image": "/images/png/upper-cabinet-one.png",
    "component": "UpperCabinetOne",
    "componentKey": "UpperCabinetOne",
    "type": "wall-cabinet-driver",
    "group": "Behind the Driver",
    "description": "Wall-mounted cabinet with built-in microwave.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Upper Left Wall Cabinet Without Microwave",
    "price": 1000,
    "image": "/images/png/upper-cabinet-two.png",
    "component": "UpperCabinetTwo",
    "componentKey": "UpperCabinetTwo",
    "type": "wall-cabinet-driver",
    "group": "Behind the Driver",
    "description": "Wall-mounted cabinet without a microwave for extra storage.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Upper Cabinet One",
    "price": 1000,
    "image": "/images/png/upper-cabinet-one.png",
    "component": "UpperCabinetOne",
    "componentKey": "UpperCabinetOne",
    "type": "wall-cabinet-driver",
    "group": "Behind the Passenger Seat",
    "description": "Wall-mounted upper cabinet.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Upper Cabinet Two",
    "price": 1000,
    "image": "/images/png/upper-cabinet-two.png",
    "component": "UpperCabinetTwo",
    "componentKey": "UpperCabinetTwo",
    "type": "wall-cabinet-driver",
    "group": "Behind the Passenger Seat",
    "description": "Upper storage for small items.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Upper Cabinet Three",
    "price": 1000,
    "image": "/images/png/upper-cabinet-three.png",
    "component": "UpperCabinetThree",
    "componentKey": "UpperCabinetThree",
    "type": "wall-cabinet-kitchen",
    "group": "Behind the Passenger Seat",
    "description": "Compact cabinet for above windows.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Upper Cabinet Four",
    "price": 1000,
    "image": "/images/png/upper-cabinet-four.png",
    "component": "UpperCabinetFour",
    "componentKey": "UpperCabinetFour",
    "type": "wall-cabinet-kitchen",
    "group": "Behind the Passenger Seat",
    "description": "Multi-compartment wall cabinet.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Standard Dinette bed",
    "price": 1000,
    "image": "/images/png/dinettebed.png",
    "component": "DinetteBed",
    "componentKey": "DinetteBed",
    "type": "dinette",
    "group": "Bed/Dinette",
    "description": "Fixed length, pairs with east-west elevator bed.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Extendable Dinette bed",
    "price": 1000,
    "image": "/images/png/bench-one.png",
    "component": "BenchOne",
    "componentKey": "BenchOne",
    "type": "dinette",
    "group": "Bed/Dinette",
    "description": "Longer length, works with south-north elevator bed.",
    "hasSink": false
  },
  // {
  //   "category": "interior",
  //   "label": "Dinette crystal velvet cushion set",
  //   "price": 1000,
  //   "image": "/images/png/bench-two.png",
  //   "component": "BenchTwo",
  //   "componentKey": "BenchTwo",
  //   "type": "dinette",
  //   "group": "Bed/Dinette",
  //   "description": "Anti-scratch, slip-resistant, and plush texture.",
  //   "hasSink": false
  // },
  // {
  //   "category": "interior",
  //   "label": "Dinette chenille fleece cushion set",
  //   "price": 1000,
  //   "image": "/images/png/bench-three.png",
  //   "component": "BenchThree",
  //   "componentKey": "BenchThree",
  //   "type": "dinette",
  //   "group": "Bed/Dinette",
  //   "description": "Durable and low-maintenance fabric.",
  //   "hasSink": false
  // },
  {

    "category": "interior",
    "label": "Dinette Dutch velvet cushion set",
    "price": 1000,
    "image": "/images/png/cushion-bed.png",
    "component": "DinetteCushionSet",
    "componentKey": "DinetteCushionSet",
    "type": "cushion",
    "group": "Bed/Dinette",
    "description": "Resistant to wear & tear, piling, and fading.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Dinette imitation linen cushion set",
    "price": 1000,
    "image": "/images/png/cushion-one.png",
    "component": "CushionOne",
    "componentKey": "CushionOne",
    "type": "cushion",
    "group": "Bed/Dinette",
    "description": "Shrinkage-resistant, easy to clean, and budget-friendly.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Dinette waterproof Oxford cushion set",
    "price": 1000,
    "image": "/images/png/cushion-two.png",
    "component": "CushionTwo",
    "componentKey": "CushionTwo",
    "type": "cushion",
    "group": "Bed/Dinette",
    "description": "Lightweight, easy-to-maintain, and PU-coated.",
    "hasSink": false
  },
  {

    "category": "interior",
    "label": "Dinette water-resistant chenille cushion set",
    "price": 1000,
    "image": "/images/png/cushion-three.png",
    "component": "CushionThree",
    "componentKey": "CushionThree",
    "type": "cushion",
    "group": "Bed/Dinette",
    "description": "Woven, thick, water & stain-resistant fabric.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Dinette cushion set Five",
    "price": 1000,
    "image": "/images/png/cushion-four.png",
    "component": "CushionFour",
    "componentKey": "CushionFour",
    "type": "cushion",
    "group": "Bed/Dinette",
    "description": "Cushion with unique texture and support.",
    "hasSink": false
  },

  // ......................

{
    "category": "interior",
    "label": "East-West Elevator Bed",
    "price": 1000,
    "image": "/images/png/elevatorbed.png",
    "component": "Elevatorbed",
    "componentKey": "Elevatorbed",
    "type": "bed",
    "group": "Bed/Dinette",
    "description": "Side-to-side bed with a standard dinette bed underneath.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "East-West Elevator Bed",
    "price": 1000,
    "image": "/images/png/swivel-table.png",
    "component": "SwivelTable",
    "componentKey": "SwivelTable",
    "type": "swiveltable",
    "group": "Bed/Dinette",
    "description": "Polished (Bamboo) or coloured (MDF) rotating table for dining and work…",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Reading Light",
    "price": 1000,
    "image": "/images/png/reading-single.png",
    "component": "ReadingLight",
    "componentKey": "ReadingLight",
    "type": "light",
    "group": "Bed/Dinette",
    "description": "Available in black and silver colours.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Outdoor Shower",
    "price": 1000,
    "image": "/images/png/shower-box-one.png",
    "component": "ShowerBox",
    "componentKey": "ShowerBox",
    "type": "showerbox",
    "group": "Bed/Dinette",
    "description": "Shower for rinsing off after outdoor activities.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Kitchen Cabinet With Refrigerator",
    "price": 1000,
    "image": "/images/png/kitchen-cabinet.png",
    "component": "KitchenCabinet",
    "componentKey": "KitchenCabinet",
    "type": "kitchen",
    "group": "Behind the Passenger Seat",
    "description": "Kitchen cabinets of different colours and styles are available.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Kitchen Backsplash",
    "price": 1000,
    "image": "/images/png/backsplash-one.png",
    "component": "BacksplashOne",
    "componentKey": "BacksplashOne",
    "type": "backsplash",
    "group": "Bed/Dinette",
    "description": "Different colours and designs are available.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Backsplash Two",
    "price": 1000,
    "image": "/images/png/backsplash-two.png",
    "component": "BacksplashTwo",
    "componentKey": "BacksplashTwo",
    "type": "backsplash",
    "group": "Bed/Dinette",
    "description": "Backsplash design two for exterior",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Backsplash Three",
    "price": 1000,
    "image": "/images/png/backsplash-three.png",
    "component": "BacksplashThree",
    "componentKey": "BacksplashThree",
    "type": "backsplash",
    "group": "Bed/Dinette",
    "description": "Backsplash design three for exterior",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Backsplash Four",
    "price": 1000,
    "image": "/images/png/backsplash-four.png",
    "component": "BacksplashFour",
    "componentKey": "BacksplashFour",
    "type": "backsplash",
    "group": "Bed/Dinette",
    "description": "Backsplash design four for exterior",
    "hasSink": false
  },
  // {
  //   "category": "interior",
  //   "label": "Reading Light",
  //   "price": 1000,
  //   "image": "/images/png/reading-single.png",
  //   "component": "ReadingLight",
  //   "componentKey": "ReadingLight",
  //   "type": "light",
  //   "group": "Bed/Dinette",
  //   "description": "Available in black and silver colours.",
  //   "hasSink": false
  // },
  // {
  //   "category": "interior",
  //   "label": "Outdoor Shower",
  //   "price": 1000,
  //   "image": "/images/png/shower-box-one.png",
  //   "component": "ShowerBox",
  //   "componentKey": "ShowerBox",
  //   "type": "showerbox",
  //   "group": "Bed/Dinette",
  //   "description": "Shower for rinsing off after outdoor activities.",
  //   "hasSink": false
  // },
  // {
  //   "category": "interior",
  //   "label": "Kitchen Cabinet With Refrigerator",
  //   "price": 1000,
  //   "image": "/images/png/kitchen-cabinet.png",
  //   "component": "KitchenCabinet",
  //   "componentKey": "KitchenCabinet",
  //   "type": "kitchen",
  //   "group": "Behind the Passenger Seat",
  //   "description": "Kitchen cabinets of different colours and styles are available.",
  //   "hasSink": false
  // },
  // {
  //   "category": "interior",
  //   "label": "Kitchen Cabinet With Refrigerator",
  //   "price": 1000,
  //   "image": "/images/png/kitchen-cabinet.png",
  //   "component": "KitchenCabinet",
  //   "componentKey": "KitchenCabinet",
  //   "type": "kitchen",
  //   "group": "Behind the Passenger Seat",
  //   "description": "Kitchen cabinets of different colours and styles are available.",
  //   "hasSink": false
  // },
  {
    "category": "interior",
    "label": "Counter Top",
    "price": 1000,
    "image": "/images/png/countertop-four.png",
    "component": "CounterTopFour",
    "componentKey": "CounterTopFour",
    "type": "counter-top",
    "group": "Behind the Passenger Seat",
    "description": "Available in different textures.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Counter Top with Undermount Sink one",
    "price": 1000,
    "image": "/images/png/undermount-sink.png",
    "component": "UndermountSink",
    "componentKey": "UndermountSink",
    "type": "counter-top",
    "group": "Behind the Passenger Seat",
    "description": "Sink mounted below the countertop.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Counter Top with Undermount Sink two",
    "price": 1000,
    "image": "/images/png/countertop-one.png",
    "component": "CounterTopOne",
    "componentKey": "CounterTopOne",
    "type": "counter-top",
    "group": "Behind the Passenger Seat",
    "description": "Primary countertop layout.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Counter Top with Undermount Sink Three",
    "price": 1000,
    "image": "/images/png/countertop-five.png",
    "component": "CounterTopFive",
    "componentKey": "CounterTopFive",
    "type": "counter-top",
    "group": "Behind the Passenger Seat",
    "description": "Modern styled counter.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Counter Top with Undermount Sink Four",
    "price": 1000,
    "image": "/images/png/countertop-three.png",
    "component": "CounterTopThree",
    "componentKey": "CounterTopThree",
    "type": "counter-top",
    "group": "Behind the Passenger Seat",
    "description": "Compact countertop setup.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Kitchen faucet",
    "price": 1000,
    "image": "/images/png/black-faucet.png",
    "component": "BlackFaucet",
    "componentKey": "BlackFaucet",
    "type": "faucet",
    "group": "Behind the Passenger Seat",
    "description": "Kitchen faucet comes in different colours and styles.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Black faucet Two",
    "price": 1000,
    "image": "/images/png/faucet-two.png",
    "component": "FaucetV2",
    "componentKey": "FaucetV2",
    "type": "faucet",
    "group": "Behind the Passenger Seat",
    "description": "Double, sleek faucet.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Silver faucet",
    "price": 1000,
    "image": "/images/png/faucet.png",
    "component": "Faucet",
    "componentKey": "Faucet",
    "type": "faucet",
    "group": "Behind the Passenger Seat",
    "description": "Double, sleek faucet.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Single Cooktop",
    "price": 1000,
    "image": "/images/png/small-stove.png",
    "component": "StoveSmall",
    "componentKey": "StoveSmall",
    "type": "stove",
    "group": "Behind the Passenger Seat",
    "description": "Compact single cooktop for cooking.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Double Cooktop",
    "price": 1000,
    "image": "/images/png/large-stove.png",
    "component": "StoveLarge",
    "componentKey": "StoveLarge",
    "type": "stove",
    "group": "Behind the Passenger Seat",
    "description": "Dual-burner cooktop for cooking.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Extended Countertop",
    "price": 1000,
    "image": "/images/png/extended-countertop.png",
    "component": "KitchenExtendedCountertop",
    "componentKey": "KitchenExtendedCountertop",
    "type": "countertop",
    "group": "Behind the Passenger Seat",
    "description": "Extra-long work surface.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Extended Countertop One",
    "price": 1000,
    "image": "/images/png/extended-countertop-one.png",
    "component": "KitchenExtendedCountertopOne",
    "componentKey": "KitchenExtendedCountertopOne",
    "type": "countertop",
    "group": "Behind the Passenger Seat",
    "description": "Extendable surface for extra kitchen space.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Extended Countertop Two",
    "price": 1000,
    "image": "/images/png/extended-countertop-two.png",
    "component": "KitchenExtendedCountertopTwo",
    "componentKey": "KitchenExtendedCountertopTwo",
    "type": "countertop",
    "group": "Behind the Passenger Seat",
    "description": "Another variation of counter extension.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Extended Countertop Three",
    "price": 1000,
    "image": "/images/png/extended-countertop-three.png",
    "component": "KitchenExtendedCountertopThree",
    "componentKey": "KitchenExtendedCountertopThree",
    "type": "countertop",
    "group": "Behind the Passenger Seat",
    "description": "Additional counter extension option.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Small Fridge",
    "price": 1000,
    "image": "/images/png/small-fridge.png",
    "component": "SmallFridge",
    "componentKey": "SmallFridge",
    "type": "appliance",
    "group": "Behind the Passenger Seat",
    "description": "Compact refrigerator.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Sink Cover One",
    "price": 1000,
    "image": "/images/png/sink-cover-one.png",
    "component": "SinkCoverOne",
    "componentKey": "SinkCoverOne",
    "type": "sink-cover",
    "group": "Behind the Passenger Seat",
    "description": "Sink cover to increase worktop space.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Sink Cover Two",
    "price": 1000,
    "image": "/images/png/sink-cover-two.png",
    "component": "SinkCoverTwo",
    "componentKey": "SinkCoverTwo",
    "type": "sink-cover",
    "group": "Behind the Passenger Seat",
    "description": "Sink cover to increase worktop space.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Sink Cover Three",
    "price": 1000,
    "image": "/images/png/sink-cover-three.png",
    "component": "SinkCoverThree",
    "componentKey": "SinkCoverThree",
    "type": "sink-cover",
    "group": "Behind the Passenger Seat",
    "description": "Removable cover for sink basin.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Sink Cover Four",
    "price": 1000,
    "image": "/images/png/sink-cover.png",
    "component": "SinkCoverFour",
    "componentKey": "UndermountSinkCover",
    "type": "sink-cover",
    "group": "Behind the Passenger Seat",
    "description": "Cover to extend counter space.",
    "hasSink": false
  },
  // {
  //   "category": "interior",
  //   "label": "Upper Cabinet Three",
  //   "price": 1000,
  //   "image": "/images/png/upper-cabinet-three.png",
  //   "component": "UpperCabinetThree",
  //   "componentKey": "UpperCabinetThree",
  //   "type": "wall-cabinet-kitchen",
  //   "group": "Behind the Passenger Seat",
  //   "description": "Compact cabinet for above windows.",
  //   "hasSink": false
  // },
  // {
  //   "category": "interior",
  //   "label": "Upper Cabinet Four",
  //   "price": 1000,
  //   "image": "/images/png/upper-cabinet-four.png",
  //   "component": "UpperCabinetFour",
  //   "componentKey": "UpperCabinetFour",
  //   "type": "wall-cabinet-kitchen",
  //   "group": "Behind the Passenger Seat",
  //   "description": "Multi-compartment wall cabinet.",
  //   "hasSink": false
  // },
  
  // {
  //   "category": "interior",
  //   "label": "Upper Cabinet One",
  //   "price": 1000,
  //   "image": "/images/png/upper-cabinet-one.png",
  //   "component": "UpperCabinetOne",
  //   "componentKey": "UpperCabinetOne",
  //   "type": "wall-cabinet-driver",
  //   "group": "Behind the Passenger Seat",
  //   "description": "Wall-mounted upper cabinet.",
  //   "hasSink": false
  // },
  // {
  //   "category": "interior",
  //   "label": "Upper Cabinet Two",
  //   "price": 1000,
  //   "image": "/images/png/upper-cabinet-two.png",
  //   "component": "UpperCabinetTwo",
  //   "componentKey": "UpperCabinetTwo",
  //   "type": "wall-cabinet-driver",
  //   "group": "Behind the Passenger Seat",
  //   "description": "Upper storage for small items.",
  //   "hasSink": false
  // },
  {
    "category": "interior",
    "label": "Shower Small",
    "price": 1000,
    "image": "/images/png/small-shower.png",
    "component": "ShowerS",
    "componentKey": "ShowerS",
    "type": "shower",
    "group": "Shower",
    "description": "28” S off-white/grey Aluminium shower box.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Shower Medium",
    "price": 1000,
    "image": "/images/png/shower.png",
    "component": "ShowerS",
    "componentKey": "ShowerS",
    "type": "shower",
    "group": "Shower",
    "description": "32” M off-white/grey Aluminium shower box.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Ceiling One",
    "price": 1000,
    "image": "/images/png/wall-ceiling-one.png",
    "component": "WallAndCeilingOne",
    "componentKey": "WallAndCeilingSeven",
    "type": "ceiling",
    "group": "Interior Build",
    "description": "Basic wall and ceiling panel for interior build.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Ceiling Two",
    "price": 1000,
    "image": "/images/png/wall-ceiling-two.png",
    "component": "WallAndCeilingTwo",
    "componentKey": "WallAndCeilingTwo",
    "type": "ceiling",
    "group": "Interior Build",
    "description": "Sleek wall and ceiling design.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Ceiling Three",
    "price": 1000,
    "image": "/images/png/wall-ceiling-three.png",
    "component": "WallAndCeilingThree",
    "componentKey": "WallAndCeilingThree",
    "type": "ceiling",
    "group": "Interior Build",
    "description": "Contemporary wall and ceiling panels.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Ceiling Four",
    "price": 1000,
    "image": "/images/png/wall-ceiling-three.png",
    "component": "WallAndCeilingThree",
    "componentKey": "WallAndCeilingThree",
    "type": "ceiling",
    "group": "Interior Build",
    "description": "Ceiling finish panels",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Wall + Ceiling + Door panel",
    "price": 1000,
    "image": "/images/png/wall-ceiling-six.png",
    "component": "WallAndCeilingSix",
    "componentKey": "WallAndCeilingSix",
    "type": "wall-ceiling-door-panel",
    "group": "Interior Build",
    "description": "Walls & doors are the same, the ceiling can be changed for contrast.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Wall + Ceiling",
    "price": 1000,
    "image": "/images/png/wall-ceiling-seven.png",
    "component": "WallAndCeilingSeven",
    "componentKey": "WallAndCeilingSeven",
    "type": "wall-ceiling",
    "group": "Interior Build",
    "description": "Choose the same wall & ceiling panels or create a contrast.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Wall Panel Two",
    "price": 1000,
    "image": "/images/png/wall-ceiling-one.png",
    "component": "WallPanels",
    "componentKey": "WallPanels",
    "type": "wall-panel",
    "group": "Interior Build",
    "description": "Decorative wall panels.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Wall Panel Three",
    "price": 1000,
    "image": "/images/png/wall-ceiling-five.png",
    "component": "WallAnsCeilingFive",
    "componentKey": "WallAnsCeilingFive",
    "type": "wall-panel",
    "group": "Interior Build",
    "description": "Elegant wall and ceiling design.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Wall Panel Four",
    "price": 1000,
    "image": "/images/png/wall-ceiling-four.png",
    "component": "WallAnsCeilingFour",
    "componentKey": "WallAnsCeilingFour",
    "type": "wall-panel",
    "group": "Interior Build",
    "description": "Modern wall and ceiling finish.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Door Panel One",
    "price": 1000,
    "image": "/images/png/door-panel-one.png",
    "component": "DoorPanelOne",
    "componentKey": "DoorPanelOne",
    "type": "door-panel",
    "group": "Interior Build",
    "description": "Decorative door panel design one..",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Door Panel Two",
    "price": 1000,
    "image": "/images/png/door-panel-two.png",
    "component": "DoorPanelTwo",
    "componentKey": "DoorPanelTwo",
    "type": "door-panel",
    "group": "Interior Build",
    "description": "Decorative door panel design one..",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Partition wall",
    "price": 1000,
    "image": "/images/png/partation-wall.png",
    "component": "PartationPanel",
    "componentKey": "PartationPanel",
    "type": "partation-panel",
    "group": "Behind the Passenger Seat",
    "description": "Customise the wall in any colour and design.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Partition wall One",
    "price": 1000,
    "image": "/images/png/partation-wall-one.png",
    "component": "PartationWallOne",
    "componentKey": "PartationWallOne",
    "type": "partation-panel",
    "group": "Behind the Passenger Seat",
    "description": "First variation of the van's partition wall.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Partition wall Two",
    "price": 1000,
    "image": "/images/png/partation-wall-two.png",
    "component": "PartationWallTwo",
    "componentKey": "PartationWallTwo",
    "type": "partation-panel",
    "group": "Behind the Passenger Seat",
    "description": "Alternative layout for van partition wall.",
    "hasSink": false
  },
  {
    "category": "interior",
    "label": "Partition wall three",
    "price": 1000,
    "image": "/images/png/partation-wall-three.png",
    "component": "PartationWallThree",
    "componentKey": "PartationWallThree",
    "type": "partation-panel",
    "group": "Behind the Passenger Seat",
    "description": "Third variation of the van's partition wall.",
    "hasSink": false
  },

];
const exteriorComponents = [

{
    "category": "exterior",
    "label": "Electric awning",
    "price": 1000,
    "image": "/images/png/awning.png",
    "component": "Awning",
    "componentKey": "Awning",
    "type": "awning",
    "group": "Right-Side",
    "description": "Extendable Motorised awning with a wind sensor.",
    "hasSink": false
  },
{
    "category": "exterior",
    "label": "Monster Box",
    "price": 1000,
    "image": "/images/png/storage-box.png",
    "component": "StorageBox",
    "componentKey": "StorageBox",
    "type": "storage",
    "group": "Rear-View",
    "description": "Weighs less than 60 lb and has locking latches to secure gear accessor.",
    "hasSink": false
  },
  {
    "category": "exterior",
    "label": "Sherpa Cargo carrier",
    "price": 1000,
    "image": "/images/png/bc.png",
    "component": "BackCarrier",
    "componentKey": "BackCarrier",
    "type": "carrier",
    "group": "Rear-View",
    "description": "Has a 100 lb load capacity to mount tires, boxes, etc.",
    "hasSink": false
  },
    {
    "category": "exterior",
    "label": "B2 Pro Box Carrier and Bike Rack",
    "price": 1000,
    "image": "/images/png/bicycle-carrier.jpg",
    "component": "BicycleCarrier",
    "componentKey": "BicycleCarrier",
    "type": "bike-carrier",
    "group": "Rear-View",
    "description": "Has a 200 lb load capacity to mount tires, boxes, etc.",
    "hasSink": false
  },
   {
    "category": "exterior",
    "label": "Powerlift bike rack",
    "price": 1000,
    "image": "/images/png/bike-carrier.jpg",
    "component": "BikeCarrier",
    "componentKey": "BikeCarrier",
    "type": "bike-carrier",
    "group": "Rear-View",
    "description": "Uses power-assisted lift to raise & lower bikes.",
    "hasSink": false
  },
{
    "category": "exterior",
    "label": "Van Rear Storage Box",
    "price": 1000,
    "image": "/images/png/rear-storage-box-topper-r.jpg",
    "component": "RearStorageBox",
    "componentKey": "RearStorageBox",
    "type": "storage-box-topper",
    "group": "Rear-View",
    "description": "Has locking patches and adds 6 cu ft of storage.",
    "hasSink": false
  },
  {
    "category": "exterior",
    "label": "Side Ladder",
    "price": 1000,
    "image": "/images/png/ladder.png",
    "component": "SideLadder",
    "componentKey": "SideLadder",
    "type": "ladder",
    "group": "Left-Side",
    "description": "Side-mounted ladder to access the roof.",
    "hasSink": false
  },
  {
    "category": "exterior",
    "label": "Bump-outs",
    "price": 1000,
    "image": "/images/png/poutwindow.png",
    "component": "PopoutWindows",
    "componentKey": "PopoutWindows",
    "type": "popout",
    "group": "Windows",
    "description": "Raptor-coated bump-out to expand the length of the bed.",
    "hasSink": false
  },
  {
    "category": "exterior",
    "label": "Flat awning-style windows",
    "price": 1000,
    "image": "/images/png/flate-window.png",
    "component": "FlatWindow",
    "componentKey": "FlatWindow",
    "type": "window",
    "group": "Windows",
    "description": "Raptor-coated bump-out to expand the length of the bed.",
    "hasSink": false
  },
  {
    "category": "exterior",
    "label": "Bubble Windows",
    "price": 1000,
    "image": "/images/png/bubble-window.png",
    "component": "BubbleWindow",
    "componentKey": "BubbleWindow",
    "type": "window",
    "group": "Windows",
    "description": "Bubble-style double-pane tinted acrylic awning windows.",
    "hasSink": false
  },

];

const systemComponents = [
  {
    "category": "system",
    "label": "12V AC",
    "price": 1000,
    "image": "/images/png/ac.png",
    "component": "Ac",
    "componentKey": "Ac",
    "type": "climate-control",
    "group": "Climate",
    "description": "12V air conditioner available in white & black colours.",
    "hasSink": false
  },
  {
    "category": "system",
    "label": "Solar",
    "price": 1000,
    "image": "/images/png/solar.png",
    "component": "Solar",
    "componentKey": "Solar",
    "type": "solar",
    "group": "Power",
    "description": "100 to 200W solar panels are available.",
    "hasSink": false
  },
  {
    "category": "system",
    "label": "Ventilation fan",
    "price": 1000,
    "image": "/images/png/max-air-fan.png",
    "component": "MaxxAirFan",
    "componentKey": "MaxxAirFan",
    "type": "ventilation",
    "group": "Ventilation",
    "description": "Roof-mounted fan for improved ventilation.",
    "hasSink": false
  },

]