/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function H12220_rear_door_right_white(props) {
  const { nodes, materials } = useGLTF('/santa-monika-layout/12220_rear_door_right_white.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={false}
        far={100}
        near={0.01}
        position={[1.872, -31.728, 3.096]}
        rotation={[1.49, 0.161, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#6113_Rear_Door_Right'].geometry}
        material={materials.color}
      />
    </group>
  )
}

useGLTF.preload('/santa-monika-layout/12220_rear_door_right_white.glb')