/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function H12220_rear_door_left_white(props) {
  const { nodes, materials } = useGLTF('/santa/monika-layout/12220_rear_door_left_white.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={false}
        far={100}
        near={0.01}
        position={[-8.162, -22.577, 1.814]}
        rotation={[1.519, -0.287, -0.042]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#12220_Rear_Door_Left_white'].geometry}
        material={materials.color}
      />
    </group>
  )
}

useGLTF.preload('/santa-monika-layout/12220_rear_door_left_white.glb')
