/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function Heather_144_layoutt(props) {
  const { nodes, materials } = useGLTF('/santa-monika-layout/heather_144_layoutt.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={false}
        far={100}
        near={0.01}
        position={[-12.09, 53.688, 8.538]}
        rotation={[1.426, 3, -0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['New_AC_-_Block_3STEPSTEP-1'].geometry}
        material={materials['color-209']}
        position={[0.012, -0.205, -0.009]}
      />
      <group position={[-1.857, -0.183, 0.89]} rotation={[0, 0.106, -Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Right_Top_3STEPSTEP-1'].geometry}
          material={materials['color-136']}
          position={[1.195, 0.012, 0.57]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Right_Left_3STEPSTEP-1'].geometry}
          material={materials['color-114']}
          position={[0, 0, 0.57]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Frame_3STEPSTEP-1'].geometry}
          material={materials['color-135']}
          position={[0.015, -0.01, 0.571]}
          rotation={[-1.597, 0.009, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Frame_-10mm_P2_3STEPSTEP-2'].geometry}
          material={materials['color-146']}
          position={[1.195, 0.009, 0.57]}
          rotation={[1.545, -0.009, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Right_Bottom_3STEPSTEP-1'].geometry}
          material={materials['color-144']}
          position={[0.004, -0.004, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Right_Insert_2STEPSTEP-1'].geometry}
          material={materials['color-138']}
          position={[0, 0.02, 0.57]}
          rotation={[-1.597, 0.009, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Frame_-10mm_P2_3STEPSTEP-1'].geometry}
          material={materials['color-146']}
          position={[0.015, 0.005, 0]}
          rotation={[1.545, -0.009, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Frame_-10mm_P1_3STEPSTEP-2'].geometry}
          material={materials['color-111']}
          position={[0.015, -0.005, -0.385]}
          rotation={[1.545, -0.009, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Frame_-10mm_P1_3STEPSTEP-1'].geometry}
          material={materials['color-111']}
          position={[0.015, 0.005, 0]}
          rotation={[1.545, -0.009, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5342_Walls_Partition_Insert_SM_3STEPSTEP-1'].geometry}
        material={materials['color-212']}
        position={[-0.024, -1.378, 1.174]}
        rotation={[Math.PI / 2, 0, 0.127]}
      />
      <group position={[-0.014, -1.751, 0.095]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
        <group rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Shower_S_Base_A_3STEPSTEP-2'].geometry}
            material={materials['color-141']}
            position={[-0.004, 0, -0.648]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Shower_S_Base_A_3STEPSTEP-1'].geometry}
            material={materials['color-141']}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Shower_S_Base_B_3STEPSTEP-1'].geometry}
            material={materials['color-109']}
            position={[-0.002, -0.05, -0.324]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
          />
        </group>
        <group position={[-0.358, -0.046, 0.647]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Shower_S_Side_RH_3STEPSTEP-1'].geometry}
            material={materials['color-124']}
            position={[0.717, 0, 0]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Shower_S_Front_Channel_3STEPSTEP-2'].geometry}
            material={materials['color-118']}
            position={[0.36, 1.854, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Shower_S_Front_Channel_3STEPSTEP-1'].geometry}
            material={materials['color-118']}
            position={[0.36, 0.03, 0]}
            rotation={[0, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Shower_S_Side_LH_3STEPSTEP-1'].geometry}
            material={materials['color-131']}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Shower_S_Back_3STEPSTEP-1'].geometry}
            material={materials['color-137']}
            position={[0.36, 0, -0.645]}
          />
        </group>
      </group>
      <group position={[-1.345, -2.338, 1.519]} rotation={[0, 0, Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5347_WallCabR_Right_3STEPSTEP-1'].geometry}
          material={materials['color-117']}
          position={[0.945, 0, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5347_WallCabR_Partition_3STEPSTEP-1'].geometry}
          material={materials['color-149']}
          position={[0.465, 0, 0.384]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5347_WallCabR_Top_Strip_3STEPSTEP-1'].geometry}
          material={materials['color-105']}
          position={[0.941, 0, 0.392]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5347_WallCabR_Shelf_3STEPSTEP-1'].geometry}
          material={materials['color-150']}
          position={[0.48, 0.005, 0.188]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5347_WallCabR_Shelf_3STEPSTEP-2'].geometry}
          material={materials['color-150']}
          position={[0.465, 0.005, 0.203]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['WallCabinet_-_Lock_3STEPSTEP-1'].geometry}
          material={materials['color-103']}
          position={[0.709, 0.011, 0.048]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['WallCabinet_-_Lock_3STEPSTEP-2'].geometry}
          material={materials['color-103']}
          position={[0.236, 0.011, 0.048]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5347_WallCabR_Back_3STEPSTEP-1'].geometry}
          material={materials['color-106']}
          position={[0.004, 0.231, 0.339]}
          rotation={[-1.317, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5347_WallCabR_Left_3STEPSTEP-1'].geometry}
          material={materials['color-104']}
          position={[0, 0, 0.392]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5347_WallCabR_Back_Strip_3STEPSTEP-1'].geometry}
          material={materials['color-123']}
          position={[0.004, 0.325, 0.017]}
          rotation={[1.679, 0, 0]}
        />
        <group position={[0.474, -0.019, 0.002]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5347_WallCabR_Door-1_3STEPSTEP-1'].geometry}
            material={materials['color-107']}
            position={[0, 0.019, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5347_WallCabR_Bottom_3STEPSTEP-1'].geometry}
          material={materials['color-148']}
          position={[0.004, 0, 0]}
        />
        <group position={[0.002, -0.019, 0.002]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5347_WallCabR_Door-1_3STEPSTEP-1_1'].geometry}
            material={materials['color-107']}
            position={[0, 0.019, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5347_WallCabR_Top_3STEPSTEP-1'].geometry}
          material={materials['color-134']}
          position={[0.004, 0.059, 0.377]}
          rotation={[-0.26, 0, 0]}
        />
      </group>
      <group position={[0.011, -2.739, 0.454]} rotation={[0, -0.033, -Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Frame_socket_Right_3STEPSTEP-1'].geometry}
          material={materials['color-130']}
          position={[0.265, 0, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Frame_socket_Left_3STEPSTEP-1'].geometry}
          material={materials['color-121']}
          position={[0, 0, 0.16]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Frame_socket_Top_3STEPSTEP-1'].geometry}
          material={materials['color-129']}
          position={[0.258, 0, 0.16]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Frame_socket_Top_3STEPSTEP-2'].geometry}
          material={materials['color-129']}
          position={[0.258, 0, 0.015]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Frame_socket_-_Assly_Panel_3STEPSTEP-1'].geometry}
          material={materials['color-119']}
          position={[0.265, 0.084, 0.16]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
      </group>
      <group position={[0.103, -1.378, 0.891]} rotation={[0, -0.104, Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Frame_-10mm_P1_3STEPSTEP-1_1'].geometry}
          material={materials['color-111']}
          position={[0, -0.004, 0]}
          rotation={[1.547, 0.009, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Frame_-10mm_P1_3STEPSTEP-2_1'].geometry}
          material={materials['color-111']}
          position={[0, -0.013, -0.385]}
          rotation={[1.547, 0.009, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Frame_-10mm_P2_3STEPSTEP-2_1'].geometry}
          material={materials['color-146']}
          position={[1.18, 0.02, 0.57]}
          rotation={[1.547, 0.009, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Frame_-10mm_P2_3STEPSTEP-1_1'].geometry}
          material={materials['color-146']}
          position={[0, -0.004, 0]}
          rotation={[1.547, 0.009, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Left_Right_3STEPSTEP-1'].geometry}
          material={materials['color-145']}
          position={[1.195, 0, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Left_Bottom_3STEPSTEP-1'].geometry}
          material={materials['color-110']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Left_Insert_3STEPSTEP-1'].geometry}
          material={materials['color-113']}
          position={[0, 0.011, -0.001]}
          rotation={[1.547, 0.009, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Frame_3STEPSTEP-1_1'].geometry}
          material={materials['color-135']}
          position={[0, 0.011, -0.001]}
          rotation={[1.547, 0.009, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5342_Wall_Windows_Left_Top_3STEPSTEP-1'].geometry}
          material={materials['color-132']}
          position={[1.191, 0.013, 0.57]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
      </group>
      <group position={[-1.274, -2.579, 0.03]} rotation={[0, 0, Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Partition_1_3STEPSTEP-1'].geometry}
          material={materials['color-27']}
          position={[0.635, 0, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Back_1_3STEPSTEP-1'].geometry}
          material={materials['color-29']}
          position={[0, 0.457, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <group position={[0.629, -0.02, 0.005]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Face_StepStool_3STEPSTEP-1'].geometry}
            material={materials['color-46']}
            position={[0.066, 0, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Bottom_3STEPSTEP-1'].geometry}
          material={materials['color-48']}
          position={[0.007, 0, 0.09]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Stiffener_3STEPSTEP-1'].geometry}
          material={materials['color-16']}
          position={[0.385, 0.057, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Stiffener_3STEPSTEP-2'].geometry}
          material={materials['color-16']}
          position={[0.051, 0.057, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <group position={[0.7, -0.019, 0.822]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Face_Drawer-2_3STEPSTEP-1'].geometry}
            material={materials['color-18']}
            position={[0.484, 0, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          />
        </group>
        <group position={[0.812, 0.457, -0.15]} rotation={[0, 0, -Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Step_Compensator_Front_3STEPSTEP-1'].geometry}
            material={materials['color-31']}
            position={[0.812, 0, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Step_Compensator_Back_3STEPSTEP-1'].geometry}
            material={materials['color-11']}
            position={[0.276, 0.17, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Step_Compensator_Right_3STEPSTEP-1'].geometry}
            material={materials['color-10']}
            position={[0.812, 0.007, 0]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Step_Compensator_Top_3STEPSTEP-1'].geometry}
            material={materials['color-15']}
            position={[0.808, 0.007, 0.15]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Step_Compensator_Bottom_3STEPSTEP-1'].geometry}
            material={materials['color-7']}
            position={[0.276, 0.007, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Step_Compensator_Left_3STEPSTEP-1'].geometry}
            material={materials['color-35']}
            position={[0.272, 0.007, 0.15]}
            rotation={[0, Math.PI / 2, 0]}
          />
        </group>
        <group position={[0.175, -0.019, 0.674]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Face_Sink_Front-3_3STEPSTEP-1'].geometry}
            material={materials['color-8']}
            position={[0.45, 0, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Top_2STEPSTEP-1'].geometry}
          material={materials['color-49']}
          position={[1.179, 0, 0.927]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Skirting_3STEPSTEP-1'].geometry}
          material={materials['color-50']}
          position={[0.627, 0.05, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
        <group position={[0, 0, -0.005]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Pullout_Sides_Lower_3STEPSTEP-3'].geometry}
            material={materials['color-28']}
            position={[0.021, 0, 0.61]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Pullout_Sides_Lower_3STEPSTEP-2'].geometry}
            material={materials['color-28']}
            position={[0.021, 0, 0.23]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Pullout_Sides_Upper_3STEPSTEP-2'].geometry}
            material={materials['color-40']}
            position={[0.021, 0, 0.805]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Pullout_Sides_Lower_3STEPSTEP-1'].geometry}
            material={materials['color-28']}
            position={[0.144, 0, 0.23]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Pullout_Bottom_3STEPSTEP-2'].geometry}
            material={materials['color-20']}
            position={[0.036, 0.007, 0.522]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Pullout_Bottom_3STEPSTEP-1'].geometry}
            material={materials['color-20']}
            position={[0.036, 0.007, 0.142]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Pullout_Front_3STEPSTEP-1'].geometry}
            material={materials['color-43']}
            position={[0.028, 0.015, 0.902]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Pullout_Back_3STEPSTEP-1'].geometry}
            material={materials['color-42']}
            position={[0.152, 0.35, 0.902]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Pullout_Bottom_3STEPSTEP-3'].geometry}
            material={materials['color-20']}
            position={[0.036, 0.007, 0.817]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Pullout_Sides_Upper_3STEPSTEP-1'].geometry}
            material={materials['color-40']}
            position={[0.144, 0, 0.805]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Pullout_Sides_Lower_3STEPSTEP-4'].geometry}
            material={materials['color-28']}
            position={[0.144, 0, 0.61]}
            rotation={[0, Math.PI / 2, 0]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Back_4STEPSTEP-1'].geometry}
          material={materials['color-17']}
          position={[0.015, 0.442, 0.105]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <group position={[0.175, -0.019, 0.09]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Face_Shutter-4_3STEPSTEP-1'].geometry}
            material={materials['color-19']}
            position={[0.45, 0, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          />
        </group>
        <group position={[0.488, 0.074, 0.167]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-_B_Step_3STEPSTEP-2'].geometry}
            material={materials['color-38']}
            position={[0.191, 0.4, 0.159]}
            rotation={[0, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-_Movable_Block_3STEPSTEP-2'].geometry}
            material={materials['color-21']}
            position={[0.19, 0.594, 0.174]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-_Movable_Block_-_Small_3STEPSTEP-1'].geometry}
            material={materials['color-41']}
            position={[0.052, 0.435, 0.174]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-Fixed_Block_3STEPSTEP-3'].geometry}
            material={materials['color-44']}
            position={[0.27, 0.205, 0.174]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-Fixed_Block_3STEPSTEP-5'].geometry}
            material={materials['color-44']}
            position={[-0.016, 0.046, 0.174]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-_B_Stand_3STEPSTEP-1'].geometry}
            material={materials['color-24']}
            position={[0.127, 0.451, 0.159]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-Fixed_Block_3STEPSTEP-1'].geometry}
            material={materials['color-44']}
            position={[0.112, 0.594, 0.174]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-_B_Step_3STEPSTEP-1'].geometry}
            material={materials['color-38']}
            position={[0.064, 0.241, 0.159]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-Fixed_Block_3STEPSTEP-2'].geometry}
            material={materials['color-44']}
            position={[0.27, 0.594, 0.174]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-Fixed_Block_3STEPSTEP-6'].geometry}
            material={materials['color-44']}
            position={[0.143, 0.046, 0.174]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-Fixed_Block_3STEPSTEP-7'].geometry}
            material={materials['color-44']}
            position={[-0.015, 0.435, 0.174]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-_B_Base_3STEPSTEP-1'].geometry}
            material={materials['color-34']}
            position={[0.142, 0.281, 0.159]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-Fixed_Block_3STEPSTEP-4'].geometry}
            material={materials['color-44']}
            position={[0.134, 0.205, 0.174]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-Fixed_Block_3STEPSTEP-8'].geometry}
            material={materials['color-44']}
            position={[0.12, 0.435, 0.174]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-_Movable_Block_3STEPSTEP-1'].geometry}
            material={materials['color-21']}
            position={[0.062, 0.046, 0.174]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-_Movable_Block_-_Small_3STEPSTEP-2'].geometry}
            material={materials['color-41']}
            position={[0.202, 0.205, 0.174]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-_A_Base_3STEPSTEP-1'].geometry}
            material={materials['color-9']}
            position={[0.142, 0.281, 0.174]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-_A_Stand_3STEPSTEP-1'].geometry}
            material={materials['color-45']}
            position={[0.127, 0.451, 0.174]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-Magnet_strip_b_3STEPSTEP-1'].geometry}
            material={materials['color-30']}
            position={[-0.038, 0.259, 0.175]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-_Magnet_strip_s_3STEPSTEP-1'].geometry}
            material={materials['color-25']}
            position={[-0.038, 0.259, 0.172]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-_A_Step_3STEPSTEP-1'].geometry}
            material={materials['color-26']}
            position={[0.064, 0.241, 0.174]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#6009_Step_Stool_-_A_Step_3STEPSTEP-2'].geometry}
            material={materials['color-26']}
            position={[0.191, 0.4, 0.174]}
            rotation={[0, 0, -Math.PI]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Left_3STEPSTEP-1'].geometry}
          material={materials['color-47']}
          position={[0, 0, 0.927]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Right_3STEPSTEP-1'].geometry}
          material={materials['color-14']}
          position={[1.186, 0, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <group position={[0.002, -0.019, 0.09]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5350_Kitchen_Heather_Face_Pullout-5_3STEPSTEP-1'].geometry}
            material={materials['color-39']}
            position={[0.169, 0, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_B_DR_Back_3STEPSTEP-1'].geometry}
          material={materials['color-52']}
          position={[0.071, 0.107, 0.003]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_B_DR_Front_3STEPSTEP-1'].geometry}
          material={materials['color-12']}
          position={[0.071, 0.427, 0.083]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_B_Drawer_Face_3STEPSTEP-1'].geometry}
          material={materials['color-13']}
          position={[0.053, 0.442, 0.116]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_T_DR_Sides_3STEPSTEP-1'].geometry}
          material={materials['color-37']}
          position={[0.718, 0, 0.905]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_T_DR_Back_3STEPSTEP-1'].geometry}
          material={materials['color-53']}
          position={[1.151, 0.394, 0.825]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Table_3STEPSTEP-1'].geometry}
          material={materials['color-33']}
          position={[0.028, 0.442, 0.851]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_B_DR_Bottom_1_3STEPSTEP-1'].geometry}
          material={materials['color-36']}
          position={[0.071, 0.1, 0.009]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_B_DR_Sides_3STEPSTEP-2'].geometry}
          material={materials['color-51']}
          position={[0.078, 0.442, 0.083]}
          rotation={[-Math.PI, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_T_DR_Front_3STEPSTEP-1'].geometry}
          material={materials['color-54']}
          position={[0.726, 0.015, 0.825]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Small_Chinese_Fridge_3STEPSTEP-1'].geometry}
          material={materials['color-32']}
          position={[0.938, 0.437, 0.419]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_B_DR_Sides_3STEPSTEP-1'].geometry}
          material={materials['color-51']}
          position={[0.342, 0.092, 0.083]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_T_DR_Sides_3STEPSTEP-2'].geometry}
          material={materials['color-37']}
          position={[1.158, 0.409, 0.905]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_T_DR_Bottom_3STEPSTEP-1'].geometry}
          material={materials['color-55']}
          position={[0.726, 0.007, 0.831]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Cutting_Board_2STEPSTEP-1'].geometry}
          material={materials['color-90']}
          position={[0.429, 0, 0.113]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Strip_3STEPSTEP-1'].geometry}
          material={materials['color-58']}
          position={[0.173, 0, 0.664]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['UnderMtg_Drawer_Slide_R_3STEPSTEP-1'].geometry}
          material={materials['color-61']}
          position={[1.315, -1.326, -0.242]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Latch_Lock_2STEPSTEP-2'].geometry}
          material={materials['color-84']}
          position={[0.087, 0.011, 0.887]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Latch_Lock_2STEPSTEP-3'].geometry}
          material={materials['color-84']}
          position={[0.214, 0.011, 0.622]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Latch_2_3STEPSTEP-1'].geometry}
          material={materials['color-75']}
          position={[0.692, -0.001, 0.712]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Extended_CounterTop_3STEPSTEP-1'].geometry}
          material={materials['wood_diffuse-1']}
          position={[-0.252, -0.023, 0.927]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_T_DR_Partition_3STEPSTEP-1'].geometry}
          material={materials['color-22']}
          position={[1.043, 0.015, 0.905]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Counter_Top_2STEPSTEP-1'].geometry}
          material={materials['color-59']}
          position={[0, -0.023, 0.927]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Partition_2_3STEPSTEP-1'].geometry}
          material={materials['color-60']}
          position={[0.181, 0, 0.098]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Extended_Plywood_3STEPSTEP-1'].geometry}
          material={materials['wood_diffuse-2']}
          position={[-0.252, -0.023, 0.912]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Ninja_Flip_Oven_3STEPSTEP-1'].geometry}
          material={materials['color-96']}
          position={[0.281, 0.226, 0.125]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Cutout_Support_1_3STEPSTEP-1'].geometry}
          material={materials['color-56']}
          position={[0.015, 0.372, 0.595]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['UnderMtg_Drawer_Slide_R_3STEPSTEP-2'].geometry}
          material={materials['color-61']}
          position={[1.315, -1.326, 0.433]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <group position={[2.346, -0.984, -0.027]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_128.geometry}
            material={materials['color-66']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_128_1.geometry}
            material={materials['color-66']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Cutout_Support_2_3STEPSTEP-1'].geometry}
          material={materials['color-57']}
          position={[0.03, 0.372, 0.595]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Oven_Partition_1_3STEPSTEP-1'].geometry}
          material={materials['color-89']}
          position={[0.173, 0, 0.558]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Oven_Partition_2_3STEPSTEP-1'].geometry}
          material={materials['color-73']}
          position={[0.416, 0, 0.098]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Attop_13X15inch_Sink_3STEPSTEP-1'].geometry}
          material={materials['color-94']}
          position={[0.4, 0.192, 0.924]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Partition_3_3STEPSTEP-1'].geometry}
          material={materials['color-62']}
          position={[0.705, 0, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <group position={[2.346, -1.309, -0.027]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_134.geometry}
            material={materials['color-66']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_134_1.geometry}
            material={materials['color-66']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Pureal_Hybrid_Filter_10Inch_3STEPSTEP-1'].geometry}
          material={materials['color-91']}
          position={[0.518, 0.377, 0.195]}
          rotation={[0, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Counter_Top_Cover_3STEPSTEP-1'].geometry}
          material={materials.wood_diffuse}
          position={[0.232, 0.049, 0.927]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['WallCabinet_Locking_Bracket_3STEPSTEP-1'].geometry}
          material={materials['color-158']}
          position={[0.182, 0.011, 0.622]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Cut_Brd_Hold_1_2STEPSTEP-1'].geometry}
          material={materials['color-76']}
          position={[0.416, 0, 0.105]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5350_Kitchen_Heather_Cut_Brd_Hold_2_2STEPSTEP-1'].geometry}
          material={materials['color-95']}
          position={[0.461, 0, 0.492]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Latch_Lock_2STEPSTEP-1'].geometry}
          material={materials['color-84']}
          position={[0.942, 0.011, 0.887]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Latch_Lock_2STEPSTEP-4'].geometry}
          material={materials['color-84']}
          position={[0.21, 0.432, 0.057]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Latch_1_3STEPSTEP-1'].geometry}
          material={materials['color-69']}
          position={[0.694, 0.036, 0.712]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Leather_Handle_3STEPSTEP-1'].geometry}
          material={materials['color-88']}
          position={[0.662, -0.021, 0.888]}
          rotation={[-Math.PI, 1.566, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Leather_Handle_Pin_3STEPSTEP-1'].geometry}
          material={materials['color-68']}
          position={[0.662, -0.031, 0.9]}
          rotation={[-Math.PI / 2, 0, -2.509]}
        />
      </group>
      <group position={[-1.536, -2.128, 1.399]} rotation={[0, 0, Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6586_Control_Panel_Left_3STEPSTEP-1'].geometry}
          material={materials['color-77']}
          position={[0, 0.015, 0.12]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6586_Control_Panel_Back_3STEPSTEP-1'].geometry}
          material={materials['color-70']}
          position={[0.004, 0.147, 0.009]}
          rotation={[1.678, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6586_Control_Panel_Top_3STEPSTEP-1'].geometry}
          material={materials['color-81']}
          position={[0.731, 0.015, 0.12]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6586_Control_Panel_Right_3STEPSTEP-1'].geometry}
          material={materials['color-93']}
          position={[0.735, 0.015, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6586_Control_Panel_Front_3STEPSTEP-1'].geometry}
          material={materials['color-71']}
          position={[0.735, 0, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6586_Control_Panel_Front_-_Extra_3STEPSTEP-1'].geometry}
          material={materials['color-72']}
          position={[0.735, 0, 0]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6586_Control_Panel_Bottom_3STEPSTEP-1'].geometry}
          material={materials['color-85']}
          position={[0.004, 0.015, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5342_Walls_Partition_L_3STEPSTEP-1'].geometry}
        material={materials['color-205']}
        position={[-0.001, 0, 0.011]}
      />
      <group position={[-0.488, -2.128, 1.519]} rotation={[0, 0, -Math.PI / 2]}>
        <group position={[0.5, -0.019, 0.002]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5346_WallCabL_Door_3STEPSTEP-1'].geometry}
            material={materials['color-115']}
            position={[0, 0.019, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5346_WallCabL_Back_3STEPSTEP-1'].geometry}
          material={materials['color-122']}
          position={[0.004, 0.291, 0.34]}
          rotation={[-1.303, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5346_WallCabL_Top_Strip_3STEPSTEP-1'].geometry}
          material={materials['color-139']}
          position={[0.992, 0, 0.392]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5346_WallCabL_Bottom_3STEPSTEP-1'].geometry}
          material={materials['color-133']}
          position={[0.004, 0, 0]}
        />
        <group position={[0.021, -0.019, 0.002]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['#5346_WallCabL_DoorL-0_3STEPSTEP-1'].geometry}
            material={materials['color-116']}
            position={[0, 0.019, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5346_WallCabL_Left_3STEPSTEP-1'].geometry}
          material={materials['color-142']}
          position={[0, 0, 0.392]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5346_WallCabL_Right_3STEPSTEP-1'].geometry}
          material={materials['color-126']}
          position={[0.996, 0, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5346_WallCabL_Shelf_3STEPSTEP-1'].geometry}
          material={materials['color-147']}
          position={[0.505, 0.008, 0.188]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['WallCabinet_-_Lock_3STEPSTEP-1_1'].geometry}
          material={materials['color-103']}
          position={[0.747, 0.011, 0.048]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5346_WallCabL_Partition_3STEPSTEP-1'].geometry}
          material={materials['color-112']}
          position={[0.49, 0, 0.384]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5346_WallCabL_Back_Strip_3STEPSTEP-1'].geometry}
          material={materials['color-140']}
          position={[0.004, 0.39, 0.017]}
          rotation={[1.679, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['WallCabinet_-_Lock_3STEPSTEP-2_1'].geometry}
          material={materials['color-103']}
          position={[0.259, 0.011, 0.048]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5346_WallCabL_Top_3STEPSTEP-1'].geometry}
          material={materials['color-143']}
          position={[0.004, 0.128, 0.377]}
          rotation={[-0.265, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5346_WallCabL_Shelf_3STEPSTEP-2'].geometry}
          material={materials['color-147']}
          position={[0.015, 0.008, 0.188]}
        />
      </group>
      <group position={[-0.629, 0.071, 0.03]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Flap_A_3STEPSTEP-1'].geometry}
          material={materials['color-174']}
          position={[0.57, 0, 0.44]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Shower_Panel_3STEPSTEP-1'].geometry}
          material={materials['color-172']}
          position={[0.041, 0.007, 0.425]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Flap_Supp_H_3STEPSTEP-1'].geometry}
          material={materials['color-23']}
          position={[0.041, 0.007, 0.41]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Water_Tank_Fresh_30G_2STEPSTEP-1'].geometry}
          material={materials['color-167']}
          position={[0.964, 0.207, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Supp_Strip_Long2_3STEPSTEP-1'].geometry}
          material={materials['color-166']}
          position={[0.579, 0.573, 0.34]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Design_Panel_B_3STEPSTEP-1'].geometry}
          material={materials['color-183']}
          position={[-0.011, 0.291, 0.37]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Flap_B_3STEPSTEP-1'].geometry}
          material={materials['color-182']}
          position={[1.382, 0, 0.44]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['WallCabinet_-_Lock_3STEPSTEP-1_2'].geometry}
          material={materials['color-103']}
          position={[0.011, 0.049, 0.315]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Top_Strip_C_3STEPSTEP-1'].geometry}
          material={materials['color-189']}
          position={[0.091, 0.565, 0.425]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Design_Panel_A_3STEPSTEP-2'].geometry}
          material={materials['color-177']}
          position={[-0.005, 0.07, 0.077]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Foldable_Flap_B_3STEPSTEP-1'].geometry}
          material={materials['color-191']}
          position={[1.382, 0.493, 0.44]}
          rotation={[0, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Design_Panel_A_3STEPSTEP-1'].geometry}
          material={materials['color-177']}
          position={[-0.005, 0.433, 0.37]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Top_Strip_A_3STEPSTEP-1'].geometry}
          material={materials['color-184']}
          position={[0, 0, 0.425]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Flap_Support_Strip_3STEPSTEP-1'].geometry}
          material={materials['color-175']}
          position={[0.091, 0, 0.385]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Top_Strip_B_3STEPSTEP-1'].geometry}
          material={materials['color-173']}
          position={[1.449, 0, 0.425]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Foldable_Flap_A_3STEPSTEP-1'].geometry}
          material={materials['color-180']}
          position={[0.57, 0.493, 0.44]}
          rotation={[0, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Door_3STEPSTEP-1'].geometry}
          material={materials['color-178']}
          position={[-0.019, 0, 0.44]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Design_Panel_B_3STEPSTEP-2'].geometry}
          material={materials['color-183']}
          position={[-0.011, 0.217, 0.37]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Design_Panel_B_3STEPSTEP-3'].geometry}
          material={materials['color-183']}
          position={[-0.011, 0.144, 0.37]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Support_Strip_3STEPSTEP-2'].geometry}
          material={materials['color-168']}
          position={[0.556, 0.618, 0.425]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Support_Small_Strip_3STEPSTEP-1'].geometry}
          material={materials['color-185']}
          position={[0.015, 0.007, 0.385]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Supp_Strip_Long1_3STEPSTEP-1'].geometry}
          material={materials['color-176']}
          position={[0.086, 0.573, 0.34]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Back_Strip_B_3STEPSTEP-1'].geometry}
          material={materials['color-186']}
          position={[0.091, 0.625, 0.44]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Support_Strip_3STEPSTEP-1'].geometry}
          material={materials['color-168']}
          position={[1.377, 0.618, 0.425]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Front_3STEPSTEP-1'].geometry}
          material={materials['color-171']}
          position={[1.445, 0, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Back_3STEPSTEP-1'].geometry}
          material={materials['color-170']}
          position={[0.08, 0.625, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Right_3STEPSTEP-1'].geometry}
          material={materials['color-188']}
          position={[1.449, 0, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Back_Strip_A_3STEPSTEP-1'].geometry}
          material={materials['color-179']}
          position={[0.091, 0.503, 0]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Support_Strip_3STEPSTEP-3'].geometry}
          material={materials['color-168']}
          position={[0.586, 0.618, 0.34]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5344_Bench_L_Bottom_Strip_3STEPSTEP-1'].geometry}
          material={materials['color-190']}
          position={[0, 0.007, 0]}
        />
      </group>
      <group position={[-0.883, -1.325, 1.768]} rotation={[0, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Rear_Cover_3STEPSTEP-1'].geometry}
          material={materials['color-199']}
          position={[0, -1.317, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Flat_2_3STEPSTEP-4'].geometry}
          material={materials['color-198']}
          position={[0.3, -0.764, 0]}
          rotation={[Math.PI, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Sliding_Base_L_3STEPSTEP-1'].geometry}
          material={materials['color-78']}
          position={[-0.403, -0.551, 0.015]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes['#6587_Elevator_Bed_E_W_-_Alluminium_Frame_New_Default_As_Machined__3STEPSTEP-1']
              .geometry
          }
          material={materials['color-86']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Second_Ceiling_3STEPSTEP-1'].geometry}
          material={materials['wood_diffuse-3']}
          position={[0, -0.741, -0.03]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Fixed_Base_3STEPSTEP-1'].geometry}
          material={materials['color-74']}
          position={[0, -0.522, 0.015]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Rear_Base_3STEPSTEP-1'].geometry}
          material={materials['color-92']}
          position={[0, -1.187, 0.015]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Circle_3STEPSTEP-2'].geometry}
          material={materials['color-80']}
          position={[-0.164, -1.055, -0.015]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Circle_3STEPSTEP-3'].geometry}
          material={materials['color-80']}
          position={[0.164, -1.055, -0.015]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Circle_3STEPSTEP-4'].geometry}
          material={materials['color-80']}
          position={[0.164, -1.055, 0]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Flat_1_3STEPSTEP-1'].geometry}
          material={materials['color-210']}
          position={[-0.3, -0.335, 0]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Circle_3STEPSTEP-1'].geometry}
          material={materials['color-80']}
          position={[-0.164, -1.055, 0]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Flat_2_3STEPSTEP-1'].geometry}
          material={materials['color-198']}
          position={[-0.3, -0.335, 0]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Sliding_Base_R_3STEPSTEP-1'].geometry}
          material={materials['color-79']}
          position={[0.403, -0.551, 0.03]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Flat_2_3STEPSTEP-2'].geometry}
          material={materials['color-198']}
          position={[0.3, -0.335, 0]}
          rotation={[Math.PI, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Flat_1_3STEPSTEP-2'].geometry}
          material={materials['color-210']}
          position={[0.3, -0.335, 0]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Flat_2_3STEPSTEP-3'].geometry}
          material={materials['color-198']}
          position={[-0.3, -0.764, 0]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Flat_1_3STEPSTEP-3'].geometry}
          material={materials['color-210']}
          position={[-0.3, -0.764, 0]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#6587_Elevator_Bed_-_Flat_1_3STEPSTEP-4'].geometry}
          material={materials['color-210']}
          position={[0.3, -0.764, 0]}
          rotation={[0, 0, -Math.PI / 2]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5342_Wall_Partition_R_Leaf_3STEPSTEP-1'].geometry}
        material={materials['color-207']}
        position={[-1.243, -1.393, 0.019]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <group position={[-1.137, -1.378, 0.03]} rotation={[0, 0, Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Left_3STEPSTEP-1'].geometry}
          material={materials['color-151']}
          position={[0, 0, 0.425]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Back_Strip_A_3STEPSTEP-1'].geometry}
          material={materials['color-127']}
          position={[1.358, 0.503, 0.44]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Support_Strip_3STEPSTEP-2'].geometry}
          material={materials['color-125']}
          position={[0.728, 0.618, 0.355]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Support_long_Strip_2_3STEPSTEP-1'].geometry}
          material={materials['color-108']}
          position={[0.065, 0.573, 0.355]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Top_Strip_A_3STEPSTEP-1'].geometry}
          material={materials['color-160']}
          position={[1.449, 0, 0.44]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Support_Strip_3STEPSTEP-1'].geometry}
          material={materials['color-125']}
          position={[1.343, 0.618, 0.425]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Flap_3STEPSTEP-2'].geometry}
          material={materials['color-155']}
          position={[1.356, 0, 0.44]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Door_3STEPSTEP-1'].geometry}
          material={materials['color-156']}
          position={[1.468, 0, 0.007]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Back_Strip_B_3STEPSTEP-1'].geometry}
          material={materials['color-120']}
          position={[1.358, 0.495, 0.44]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Flap_3STEPSTEP-1'].geometry}
          material={materials['color-155']}
          position={[0.711, 0, 0.44]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Front_3STEPSTEP-1'].geometry}
          material={nodes['#5345_Bench_R_Front_3STEPSTEP-1'].material}
          position={[1.449, 0, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Back_1_3STEPSTEP-1'].geometry}
          material={materials['color-152']}
          position={[0.004, 0.625, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Support_Strip_3STEPSTEP-3'].geometry}
          material={materials['color-125']}
          position={[0.698, 0.618, 0.425]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Support_Strip_3STEPSTEP-4'].geometry}
          material={materials['color-125']}
          position={[0.072, 0.618, 0.355]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Support_Long_Strip_4STEPSTEP-1'].geometry}
          material={materials['color-128']}
          position={[0.721, 0.573, 0.355]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Support_Small_Strip_3STEPSTEP-1'].geometry}
          material={materials['color-153']}
          position={[1.434, 0.007, 0.425]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Top_Strip_B_3STEPSTEP-1'].geometry}
          material={materials['color-163']}
          position={[0, 0.625, 0.425]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Top_Strip_C_3STEPSTEP-1'].geometry}
          material={materials['color-154']}
          position={[0.065, 0.565, 0.425]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Battery_Box_Strip_3STEPSTEP-1'].geometry}
          material={materials['color-165']}
          position={[0.015, 0.015, 0.238]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Design_Panel_B_3STEPSTEP-2'].geometry}
          material={materials['color-162']}
          position={[1.454, 0.217, 0.37]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['WallCabinet_-_Lock_3STEPSTEP-1_3'].geometry}
          material={materials['color-103']}
          position={[1.438, 0.049, 0.315]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Design_Panel_A_3STEPSTEP-2'].geometry}
          material={materials['color-161']}
          position={[1.46, 0.433, 0.37]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Battery_Box_Supports_3STEPSTEP-1'].geometry}
          material={materials['color-181']}
          position={[0.08, 0.352, 0]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Battery_Box_Top_3STEPSTEP-1'].geometry}
          material={materials['color-187']}
          position={[0.015, 0.015, 0.238]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Battery_Box_Back_3STEPSTEP-1'].geometry}
          material={materials['color-164']}
          position={[0.01, 0.338, 0.238]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Battery_Box_Supports_3STEPSTEP-2'].geometry}
          material={materials['color-181']}
          position={[0.525, 0.352, 0]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['WallCabinet_Locking_Bracket_3STEPSTEP-1_1'].geometry}
          material={materials['color-158']}
          position={[1.438, 0.016, 0.315]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Design_Panel_B_3STEPSTEP-1'].geometry}
          material={materials['color-162']}
          position={[1.454, 0.144, 0.37]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Design_Panel_B_3STEPSTEP-3'].geometry}
          material={materials['color-162']}
          position={[1.454, 0.291, 0.37]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Separator_3STEPSTEP-1'].geometry}
          material={materials['color-169']}
          position={[0.698, 0.015, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Flap_Support_Strip_3STEPSTEP-1'].geometry}
          material={materials['color-157']}
          position={[0.067, 0, 0.385]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Bottom_Strip_3STEPSTEP-1'].geometry}
          material={materials['color-159']}
          position={[1.358, 0.007, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Battery_Box_Inverter_3STEPSTEP-1'].geometry}
          material={materials['color-192']}
          position={[0.06, 0.352, 0.307]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Design_Panel_A_3STEPSTEP-1'].geometry}
          material={materials['color-161']}
          position={[1.454, 0.07, 0.37]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5345_Bench_R_Battery_Box_Supports_3STEPSTEP-3'].geometry}
          material={materials['color-181']}
          position={[0.355, 0.352, 0]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5342_Wall_Window_Frame_BD_3STEPSTEP-1'].geometry}
        material={materials['color-196']}
        position={[0.002, -2.535, 0.867]}
        rotation={[-Math.PI, -1.467, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Chinese_Fan_Model_3STEPSTEP-1'].geometry}
        material={materials['color-204']}
        position={[0.007, 0.011, -0.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5342_Walls_Partition_Bathroom_3STEPSTEP-1'].geometry}
        material={materials['color-195']}
        position={[-0.001, -0.736, 0.011]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5342_Wall_Above_Driver_3STEPSTEP-1'].geometry}
        material={materials['color-211']}
        position={[0, 1.041, -0.008]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5342_Walls_Partition_Bracket_SM_3STEPSTEP-1'].geometry}
        material={materials['color-200']}
        position={[-0.037, -1.401, 1.417]}
        rotation={[-Math.PI / 2, 0, 3.014]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5342_Walls_Partition_Bracket_SM_3STEPSTEP-2'].geometry}
        material={materials['color-200']}
        position={[0.025, -1.401, 0.935]}
        rotation={[-Math.PI / 2, 0, -0.127]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['L_Track_3STEPSTEP-2'].geometry}
        material={materials['color-194']}
        position={[-0.345, -2.128, 0.95]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#6113_Rear_Door_Right_3STEPSTEP-1'].geometry}
        material={materials['color-201']}
        position={[1.401, 1.853, 0.246]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#346_Window_Interior_Frame_(Plastic)_3STEPSTEP-1'].geometry}
        material={materials['color-203']}
        position={[-1.806, -0.788, 1.171]}
        rotation={[3.071, 1.439, -1.501]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#6113_Rear_Door_Left_3STEPSTEP-1'].geometry}
        material={materials['color-208']}
        position={[1.314, 1.853, 0.248]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Piller_Arc_3STEPSTEP-1'].geometry}
        material={materials['color-202']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#346_Window_Interior_Frame_(Plastic)_3STEPSTEP-2'].geometry}
        material={materials['color-203']}
        position={[0.051, -0.788, 1.172]}
        rotation={[3.069, -1.443, 1.498]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['L_Track_3STEPSTEP-1'].geometry}
        material={materials['color-194']}
        position={[-0.345, -2.128, 0.35]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['vertical_Planks_3STEPSTEP-1'].geometry}
        material={materials['wood_diffuse-4']}
        position={[-0.653, -2.128, 1.911]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_252.geometry}
        material={materials['color-197']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_252_1.geometry}
        material={materials['color-197']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_267.geometry}
        material={materials['color-215']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_267_1.geometry}
        material={materials['color-215']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_267_2.geometry}
        material={materials['wood_diffuse-5']}
      />
    </group>
  )
}

useGLTF.preload('/santa-monika-layout/heather_144_layoutt.glb')
