/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function Layout_2_five___slated_wallnut(props) {
  const { nodes, materials } = useGLTF('/santa-monika-layout/layout_2.5___slated_wallnut.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={false}
        far={100}
        near={0.01}
        position={[12.537, -31.055, 13.005]}
        rotation={[1.153, 0.395, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={materials['polished walnut 2d']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0_1.geometry}
        material={materials['polished walnut 2d']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0_2.geometry}
        material={materials.color}
      />
    </group>
  )
}

useGLTF.preload('/santa-monika-layout/layout_2.5___slated_wallnut.glb')

