/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function Layout_4___shiplap_nw(props) {
  const { nodes, materials } = useGLTF('/santa-monika-layout/layout_4___shiplap_n&w.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={false}
        far={100}
        near={0.01}
        position={[-6.958, -35.049, 7.036]}
        rotation={[1.391, -0.17, 0.007]}
      />
      <mesh castShadow receiveShadow geometry={nodes.mesh_0.geometry} material={materials.color} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0_1.geometry}
        material={materials.color}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0_2.geometry}
        material={materials['natural stain']}
      />
    </group>
  )
}

useGLTF.preload('/santa-monika-layout/layout_4___shiplap_n&w.glb')