/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function Layout_six___shiplap_nw(props) {
  const { nodes, materials } = useGLTF('santa-monika-layout/layout_6___shiplap_n&w.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={false}
        far={100}
        near={0.01}
        position={[-4.97, -35.264, 6.734]}
        rotation={[1.407, -0.111, -0.023]}
      />
      <mesh castShadow receiveShadow geometry={nodes.mesh_0.geometry} material={materials.color} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0_1.geometry}
        material={materials.color}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0_2.geometry}
        material={materials['natural stain']}
      />
    </group>
  )
}

useGLTF.preload('/santa-monika-layout/layout_6___shiplap_n&w.glb')
