/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function Layout_2_five___shiplap_ww(props) {
  const { nodes, materials } = useGLTF('/santa-monika-layout/layout_2.5___shiplap_w&w.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={false}
        far={100}
        near={0.01}
        position={[-12.92, 25.526, 20.482]}
        rotation={[-0.932, -0.357, -2.863]}
      />
      <mesh castShadow receiveShadow geometry={nodes.mesh_0.geometry} material={materials.color} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0_1.geometry}
        material={materials.color}
      />
    </group>
  )
}

useGLTF.preload('/santa-monika-layout/layout_2.5___shiplap_w&w.glb')