/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function Layout_4___slated_wallnut(props) {
  const { nodes, materials } = useGLTF('/santa-monika-layout/layout_4___slated_wallnut.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={false}
        far={100}
        near={0.01}
        position={[-6.227, 30.753, 14.805]}
        rotation={[-1.157, -0.146, 3.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={materials['polished walnut 2d']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0_1.geometry}
        material={materials['polished walnut 2d']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0_2.geometry}
        material={materials.color}
      />
    </group>
  )
}

useGLTF.preload('/santa-monika-layout/layout_4___slated_wallnut.glb')