/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function Layout_6___slated_wallnut(props) {
  const { nodes, materials } = useGLTF('/santa-monika-layout/layout_6___slated_wallnut.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={false}
        far={100}
        near={0.01}
        position={[10.331, 29.173, 7.46]}
        rotation={[-1.378, 0.287, 3.044]}
      />
      <mesh castShadow receiveShadow geometry={nodes.mesh_0.geometry} material={materials.color} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0_1.geometry}
        material={materials['polished walnut 2d']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0_2.geometry}
        material={materials['polished walnut 2d']}
      />
    </group>
  )
}

useGLTF.preload('/santa-monika-layout/layout_6___slated_wallnut.glb')

