/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function Layout_6___shiplap_ww(props) {
  const { nodes, materials } = useGLTF('/santa-monika-layout/layout_6___shiplap_w&w.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={false}
        far={100}
        near={0.01}
        position={[-12.381, -33.343, 11.936]}
        rotation={[1.243, -0.308, -0.08]}
      />
      <mesh castShadow receiveShadow geometry={nodes.mesh_0.geometry} material={materials.color} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0_1.geometry}
        material={materials.color}
      />
    </group>
  )
}

useGLTF.preload('/santa-monika-layout/layout_6___shiplap_w&w.glb')