/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function Layout_2_five___shiplap_nw(props) {
  const { nodes, materials } = useGLTF('/santa-monika-layout/layout_2.5___shiplap_n&w.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={false}
        far={100}
        near={0.01}
        position={[2.853, 32.529, 3.043]}
        rotation={[-1.515, 0.111, 3.098]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={materials['natural stain']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0_1.geometry}
        material={materials.color}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0_2.geometry}
        material={materials.color}
      />
    </group>
  )
}

useGLTF.preload('/santa-monika-layout/layout_2.5___shiplap_n&w.glb')