/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function wallcabl_white(props) {
  const { nodes, materials } = useGLTF('/santa-monika-layout/12220_wallcabl_white.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={false}
        far={100}
        near={0.01}
        position={[6.769, -6.535, 4.035]}
        rotation={[1.048, 0.686, 0.357]}
      />
      <group position={[0.021, -0.019, 0.002]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5346_WallCabL_DoorL-1_1'].geometry}
          material={nodes['#5346_WallCabL_DoorL-1_1'].material}
          position={[0, 0.019, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5346_WallCabL_Bottom-1'].geometry}
        material={nodes['#5346_WallCabL_Bottom-1'].material}
        position={[0.004, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5346_WallCabL_Right-1'].geometry}
        material={nodes['#5346_WallCabL_Right-1'].material}
        position={[0.996, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5346_WallCabL_Back-1'].geometry}
        material={nodes['#5346_WallCabL_Back-1'].material}
        position={[0.004, 0.291, 0.34]}
        rotation={[-1.303, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5346_WallCabL_Partition-1'].geometry}
        material={nodes['#5346_WallCabL_Partition-1'].material}
        position={[0.49, 0, 0.384]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5346_WallCabL_Top-2'].geometry}
        material={nodes['#5346_WallCabL_Top-2'].material}
        position={[0.004, 0.128, 0.377]}
        rotation={[-0.265, 0, 0]}
      />
      <group position={[0.5, -0.019, 0.002]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['#5346_WallCabL_Door-1'].geometry}
          material={nodes['#5346_WallCabL_Door-1'].material}
          position={[0, 0.019, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5346_WallCabL_Shelf-2'].geometry}
        material={nodes['#5346_WallCabL_Shelf-2'].material}
        position={[0.015, 0.008, 0.188]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['WallCabinet_-_Lock-2'].geometry}
        material={nodes['WallCabinet_-_Lock-2'].material}
        position={[0.259, 0.011, 0.048]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5346_WallCabL_Shelf-1'].geometry}
        material={nodes['#5346_WallCabL_Shelf-1'].material}
        position={[0.505, 0.008, 0.188]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5346_WallCabL_Back_Strip-1'].geometry}
        material={nodes['#5346_WallCabL_Back_Strip-1'].material}
        position={[0.004, 0.39, 0.017]}
        rotation={[1.679, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5346_WallCabL_Top_Strip-1'].geometry}
        material={nodes['#5346_WallCabL_Top_Strip-1'].material}
        position={[0.992, 0, 0.392]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['WallCabinet_-_Lock-1'].geometry}
        material={nodes['WallCabinet_-_Lock-1'].material}
        position={[0.747, 0.011, 0.048]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#5346_WallCabL_Left-1'].geometry}
        material={nodes['#5346_WallCabL_Left-1'].material}
        position={[0, 0, 0.392]}
        rotation={[0, Math.PI / 2, 0]}
      />
    </group>
  )
}

useGLTF.preload('/santa-monika-layout/12220_wallcabl_white.glb')

